SELECT NOMBRE, TIPO FROM CICLOFORM WHERE TIPO= 'GRADO SUPERIOR';

SELECT NOMBRE, AP1, AP2, DIRECCION FROM DATOS_PERSONALES WHERE TIPO='PROFESOR';
SELECT NOMBRE, AP1, AP2, DIRECCION FROM DATOS_PERSONALES, PROFESOR WHERE DNI=DNI_PROFESOR;

SELECT NOMBRE FROM ASIGNATURA WHERE NUMHORAS BETWEEN 150 AND 250;

SELECT NOMBRE , CUENTA FROM DATOS_PERSONALES, PROFESOR WHERE DNI=DNI_PROFESOR;

SELECT DNI_ALUMNO FROM MATRICULA WHERE COD_ASIG=3;

SELECT DNI_PROFESOR FROM idiomaprof WHERE cod_idioma=20;

SELECT NOMBRE FROM asignatura WHERE dni_profesor LIKE '89621477%';

SELECT DNI FROM DATOS_PERSONALES WHERE NOMBRE IN ('ANDORRA', 'LUIS');